name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install Dependencies
        run: npm install
        
      - name: Build Docker image
        run: docker build -t giobmoro/project-web-devops-as2:1.1 .

      - name: Log into Docker Hub
        run: echo "${{ secrets.DOCKER_ACCESS_TOKEN }}" | docker login --username giobmoro --password-stdin

      - name: Push Docker image to Docker Hub
        run: docker push giobmoro/project-web-devops-as2:1.1
          
  security-test:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: ZAP Scan
        uses: zaproxy/action-baseline@v0.12.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          docker_name: 'giobmoro/project-web-devops-as2:1.1'
          target: 'https://github.com/giobmoro/project-web-devops/'
          rules_file_name: '.zap/rules.tsv'
          cmd_options: '-a'

  deploy:
    runs-on: ubuntu-latest
    needs: security-test

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    
    - name: Run container
      run: docker-compose up -d 
    
    - uses: luisboto/ngrok-tunnel-action@v0.1.7.2
      with:
        timeout: 1h
        port: 8080
        ngrok_authtoken: ${{ secrets.NGROK_TOKEN }}
        tunnel_type: http
        save_url_to_filename: tunnelURL.md
